# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
import webbrowser
import float
from threading import Thread

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 851)
        MainWindow.setStyleSheet("background-color: rgb(5, 0, 30);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gif = QtWidgets.QLabel(self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(140, -110, 871, 631))
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap(":/maal masala/__02-____ (1).gif"))
        self.movie = QtGui.QMovie(":/maal masala/__02-____ (1).gif")
        self.gif.setMovie(self.movie)
        self.movie.start()
        self.gif.setScaledContents(True)
        self.gif.setObjectName("gif")

        self.google = QtWidgets.QPushButton(self.centralwidget)
        self.google.setGeometry(QtCore.QRect(21, 287, 98, 94))
        self.google.setMouseTracking(False)
        self.google.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/maal masala/Google__G__Logo.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.google.setIcon(icon)
        self.google.setIconSize(QtCore.QSize(50, 50))
        self.google.setObjectName("google")
        self.google.clicked.connect(lambda: webbrowser.open("https://www.google.com"))

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(900, 30, 171, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/maal masala/float-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 380, 831, 371))
        self.textEdit.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"color: white;")
        self.textEdit.setObjectName("textEdit")
        self.whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.whatsapp.setEnabled(True)
        self.whatsapp.setGeometry(QtCore.QRect(21, 185, 98, 94))
        self.whatsapp.setMouseTracking(False)
        self.whatsapp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/maal masala/sm_5b321c99945a2-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.whatsapp.setIcon(icon1)
        self.whatsapp.setIconSize(QtCore.QSize(85, 85))
        self.whatsapp.setObjectName("whatsapp")
        self.whatsapp.clicked.connect(lambda: webbrowser.open("https://web.whatsapp.com/"))

        self.youtube = QtWidgets.QPushButton(self.centralwidget)
        self.youtube.setGeometry(QtCore.QRect(21, 83, 98, 94))
        self.youtube.setMouseTracking(False)
        self.youtube.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/maal masala/red-flag-icon-youtube-logo-icon-design-youtube-play-buttons-arrow-rectangle-symbol-png-clipart-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.youtube.setIcon(icon2)
        self.youtube.setIconSize(QtCore.QSize(75, 85))
        self.youtube.setObjectName("youtube")
        self.youtube.clicked.connect(lambda: webbrowser.open("https://www.youtube.com"))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import assets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
