# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Float-The-Voice-Assistance\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import assets
import threading
import io
import webbrowser
from float import voice_assistant


class QTextEditStream(io.TextIOBase):
    def __init__(self, text_edit):
        self.text_edit = text_edit

    def write(self, string):
        self.text_edit.moveCursor(QtGui.QTextCursor.End)
        self.text_edit.insertPlainText(string)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 851)
        MainWindow.setStyleSheet("background-color: rgb(5, 0, 30);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gif = QtWidgets.QLabel(self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(140, -110, 871, 631))
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap(":/maal masala/__02-____ (1).gif"))
        self.movie = QtGui.QMovie(":/maal masala/__02-____ (1).gif")
        self.gif.setMovie(self.movie)
        self.movie.start()
        self.gif.setScaledContents(True)
        self.gif.setObjectName("gif")


        self.google = QtWidgets.QPushButton(self.centralwidget)
        self.google.setGeometry(QtCore.QRect(21, 287, 98, 94))
        self.google.setMouseTracking(False)
        self.google.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/maal masala/Google__G__Logo.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.google.setIcon(icon)
        self.google.setIconSize(QtCore.QSize(50, 50))
        self.google.setObjectName("google")
        self.google.clicked.connect(lambda: webbrowser.open("https://www.google.com"))


        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(900, 30, 171, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/maal masala/float-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.whatsapp.setEnabled(True)
        self.whatsapp.setGeometry(QtCore.QRect(21, 185, 98, 94))
        self.whatsapp.setMouseTracking(False)
        self.whatsapp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/maal masala/sm_5b321c99945a2-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.whatsapp.setIcon(icon1)
        self.whatsapp.setIconSize(QtCore.QSize(85, 85))
        self.whatsapp.setObjectName("whatsapp")
        self.whatsapp.clicked.connect(lambda: webbrowser.open("https://web.whatsapp.com/"))


        self.youtube = QtWidgets.QPushButton(self.centralwidget)
        self.youtube.setGeometry(QtCore.QRect(21, 83, 98, 94))
        self.youtube.setMouseTracking(False)
        self.youtube.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/maal masala/red-flag-icon-youtube-logo-icon-design-youtube-play-buttons-arrow-rectangle-symbol-png-clipart-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.youtube.setIcon(icon2)
        self.youtube.setIconSize(QtCore.QSize(75, 85))
        self.youtube.setObjectName("youtube")
        self.youtube.clicked.connect(lambda: webbrowser.open("https://www.youtube.com"))
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(510, 750, 141, 51))
        self.start_button.setIconSize(QtCore.QSize(30, 30))
        self.start_button.setObjectName("start_button")
        self.start_button.setStyleSheet("border: 2px solid white;")  #add border white color
        self.start_button.setStyleSheet("font-size: 20px; color: white;") #Increase text size and set text color to white
        self.start_button.clicked.connect(self.start_button_clicked)

        self.console_output = QtWidgets.QTextEdit(self.centralwidget)
        self.console_output.setGeometry(QtCore.QRect(130, 400, 901, 331))
        self.console_output.setObjectName("console_output")
        self.console_output.setStyleSheet("color: white;")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.console_output.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_button.setText(_translate("MainWindow", "START"))

    def start_button_clicked(self):
        """Handles start button click event."""
        # Redirect stdout to console output widget
        sys.stdout = QTextEditStream(self.console_output)

        # Start voice_assistant function in a separate thread
        thread = threading.Thread(target=voice_assistant)
        thread.start()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.start_button.click()  # Programmatically click start button
    sys.exit(app.exec_())
    # voice_assistant() # Call voice_assistant function


