# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 737)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.youtube = QtWidgets.QPushButton(self.centralwidget)
        self.youtube.setGeometry(QtCore.QRect(71, 202, 157, 55))
        self.youtube.setAutoFillBackground(False)
        self.youtube.setStyleSheet("color: rgb(72, 117, 177);\n"
"font: 81 20pt \"Montserrat ExtraBold\";\n"
"border-color: rgb(48, 79, 157);")
        self.youtube.setObjectName("youtube")
        self.browser = QtWidgets.QPushButton(self.centralwidget)
        self.browser.setGeometry(QtCore.QRect(520, 200, 157, 55))
        self.browser.setAutoFillBackground(False)
        self.browser.setStyleSheet("color: rgb(72, 117, 177);\n"
"font: 81 20pt \"Montserrat ExtraBold\";\n"
"border-color: rgb(48, 79, 157);")
        self.browser.setObjectName("browser")
        self.whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.whatsapp.setGeometry(QtCore.QRect(280, 202, 192, 55))
        self.whatsapp.setAutoFillBackground(False)
        self.whatsapp.setStyleSheet("color: rgb(72, 117, 177);\n"
"font: 81 20pt \"Montserrat ExtraBold\";\n"
"border-color: rgb(48, 79, 157);")
        self.whatsapp.setObjectName("whatsapp")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(750, 10, 258, 269))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Time = QtWidgets.QTextBrowser(self.layoutWidget)
        self.Time.setAutoFillBackground(True)
        self.Time.setStyleSheet("background-color: Transparent;\n"
"border-radius: None;")
        self.Time.setObjectName("Time")
        self.verticalLayout.addWidget(self.Time)
        self.Date = QtWidgets.QTextBrowser(self.layoutWidget)
        self.Date.setAutoFillBackground(True)
        self.Date.setStyleSheet("background-color: Transparent;\n"
"border-radius: None;")
        self.Date.setObjectName("Date")
        self.verticalLayout.addWidget(self.Date)
        self.Day = QtWidgets.QTextBrowser(self.layoutWidget)
        self.Day.setAutoFillBackground(True)
        self.Day.setStyleSheet("background-color: Transparent;\n"
"border-radius: None;")
        self.Day.setObjectName("Day")
        self.verticalLayout.addWidget(self.Day)
        self.conversationbox = QtWidgets.QTextEdit(self.centralwidget)
        self.conversationbox.setGeometry(QtCore.QRect(530, 300, 471, 371))
        self.conversationbox.setStyleSheet("color: rgb(72, 117, 177);\n"
"font: 81 20pt \"Montserrat ExtraBold\";\n"
"border-color: rgb(72, 117, 177);")
        self.conversationbox.setObjectName("conversationbox")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(990, 300, 16, 371))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 161, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/red-flag-icon-youtube-logo-icon-design-youtube-play-buttons-arrow-rectangle-symbol-png-clipart-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 20, 191, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/sm_5b321c99945a2-removebg-preview.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 20, 191, 181))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/pngtree-browser-icon-image_1144676-removebg-preview.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-150, 160, 811, 571))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/images/untitled-4.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.youtube.raise_()
        self.browser.raise_()
        self.whatsapp.raise_()
        self.layoutWidget.raise_()
        self.conversationbox.raise_()
        self.verticalScrollBar.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.youtube.setText(_translate("MainWindow", "Youtube"))
        self.browser.setText(_translate("MainWindow", "Browser"))
        self.whatsapp.setText(_translate("MainWindow", "Whatsapp"))
import res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
